// Copies blueimp-md5 from node_modules into the extension as an ES module.
// Web Crypto has no MD5, but the RTM API requires MD5 request signatures.
// Run via `make vendor` after Renovate bumps blueimp-md5; CI fails if the copy is stale.
import { readFile, writeFile } from 'node:fs/promises';

const pkg = JSON.parse(await readFile('node_modules/blueimp-md5/package.json', 'utf8'));
const source = await readFile('node_modules/blueimp-md5/js/md5.js', 'utf8');

const output = `// Generated by scripts/vendor.mjs from blueimp-md5@${pkg.version} (MIT). Do not edit.
/* eslint-disable */
const module = { exports: {} };
${source}
export default module.exports;
`;

await writeFile('extension/vendor/md5.js', output);
console.log(`Vendored blueimp-md5@${pkg.version} to extension/vendor/md5.js`);
